apiVersion: apps/v1
kind: Deployment

metadata:
  name: sample-python-deployment
  namespace: development

  labels:
    app: sample-python-app
    environment: development

spec:
  replicas: 1

  selector:
    matchLabels:
      app: sample-python-app

  template:
    metadata:
      labels:
        app: sample-python-app
        environment: development

    spec:
      containers:
        - name: sample-python-container

          image: localhost:5001/sample-python-app:v1

          imagePullPolicy: Always

          ports:
            - containerPort: 5000

          securityContext:
            privileged: false

          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"

          readinessProbe:
            httpGet:
              path: /health
              port: 5000

            initialDelaySeconds: 5
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /health
              port: 5000

            initialDelaySeconds: 15
            periodSeconds: 20